version: '3.6'

services:
  redis:
    restart: always
    image: redis:6.2-alpine
    container_name: redis-idp
    ports:
      - "6379:6379"
    command:
      - --loglevel warning
    volumes:
      - redis-data:/data:Z

volumes:
  redis-data:
