version: '3.6'

services:
  postgresql:
    restart: always
    # windows users
    # image: stellirin/postgres-windows

    # unix users
    image: postgres
    container_name: postgres-idp
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql:Z
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST_AUTH_METHOD=trust
      # - DB_EXTENSION=
      # - POSTGRES_MULTIPLE_DATABASES=

volumes:
  postgresql-data:
